#!/bin/bash

set $mod Mod4
set $term --no-startup-id $TERMINAL

set $shutdown sudo -A shutdown -h now
set $reboot sudo -A reboot
set $netrefresh --no-startup-id sudo -A systemctl restart NetworkManager
set $hibernate sudo -A systemctl hibernate

set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8: Games"
set $ws9 "9: Music"
set $ws10 "10: Waiting"

workspace "1"           output eDP-1
workspace "2"           output eDP-1
workspace "3"           output eDP-1
workspace "4"           output eDP-1
workspace "5"           output eDP-1
workspace "6"           output eDP-1
workspace "7"           output eDP-1
workspace "8: Games"    output HDMI-1
workspace "9: Music"    output HDMI-1
workspace "10: Waiting" output HDMI-1

set $inner_gaps 10
set $outer_gaps 0
gaps inner $inner_gaps
gaps outer $outer_gaps

for_window [class="^.*"] border pixel 2
for_window [instance="dropdown_*"] floating enable
for_window [instance="dropdown_*"] move scratchpad
for_window [instance="dropdown_*"] sticky enable
for_window [instance="dropdown_*"] scratchpad show
for_window [instance="dropdown_tmuxdd"] resize set 625 450
for_window [instance="dropdown_dropdowncalc"] resize set 800 300
for_window [instance="dropdown_*"] move position center
for_window [class="Pinentry"] sticky enable
for_window [class="sent"] border pixel 0px
for_window [class="Spotify"] move workspace $ws9
for_window [class="libreoffice"] move workspace $ws4
for_window [window_role="GtkFileChooserDialog"] resize set 800 600
for_window [window_role="GtkFileChooserDialog"] move position center
for_window [title="Default - Wine desktop"] floating enable
for_window [title="Picture-in-Picture"] resize set 1000 562
for_window [title="Picture-in-Picture"] move position center
assign [class="Gimp"] → $ws5

bar {
		# font pango:Source Sans Pro-10 10
    font pango:FreeMono 10
		# font pango:DroidSansMono Nerd Font 10
    status_command i3blocks
    colors {
				background					#222222
				statusline					#aaaaaa
				focused_workspace		#fdf6e3 #222222 #00afff
        active_workspace		#fdf6e3 #222222 #00afff
				inactive_workspace	#222222 #aaaaaa #222222
				urgent_workspace		#222222 #b71c1c #fdf6e3
    }
		position top mode dock
    modifier None
}
client.focused					#073642 #095d4a #fdf6e3 #a8c6f2
client.focused_inactive #073642 #073642 #fdf6e3 #a8c6f2
client.unfocused				#073642 #073642 #a8c6f2 #a8c6f2
client.urgent						#d33682 #530615 #fdf6e3 #e5786d

# ---- Mod ----
bindsym $mod+Return		exec $term
bindsym $mod+space		focus mode_toggle
bindsym $mod+Escape		workspace prev
bindsym $mod+grave		exec --no-startup-id dmenuunicode
bindsym $mod+Insert		exec --no-startup-id showclip
# bindsym $mod+BackSpace
bindsym $mod+q			[con_id="__focused__" instance="^(?!dropdown_).*$"] kill
bindsym $mod+w			exec --no-startup-id $BROWSER
bindsym $mod+e			exec $term -e neomutt
bindsym $mod+r			exec $term -e lf
bindsym $mod+t			split toggle
bindsym $mod+y			exec --no-startup-id st -e calcurse
bindsym $mod+u			exec --no-startup-id ddspawn tmuxdd
bindsym $mod+i			exec $term -e htop
bindsym $mod+o			sticky toggle
bindsym $mod+p			exec --no-startup-id playerctl play-pause
bindsym $mod+a			exec --no-startup-id ddspawn dropdowncalc -f mono:pixelsize=24
bindsym $mod+s			gaps inner current plus 5
bindsym $mod+d			exec --no-startup-id dmenu_run
bindsym $mod+f			fullscreen toggle
bindsym $mod+g			workspace prev
bindsym $mod+h			focus left
bindsym $mod+j			focus down
bindsym $mod+k			focus up
bindsym $mod+l			focus right
bindsym $mod+z			gaps outer current plus 5
bindsym $mod+x			exec --no-startup-id playerctl -a pause ;; exec --no-startup-id i3lock-fancy
bindsym $mod+c			exec --no-startup-id cabl
bindsym $mod+v			exec --no-startup-id setbg
bindsym $mod+b			bar mode toggle
#bindsym $mod+n			exec --no-startup-id notify-send "$(khal list -f '' -df '{bold}{name}' today today)" "$(khal list -f '{title}' -df '' today today)"
# bindsym $mod+m			exec --no-startup-id $term -e ncmpcpp
bindsym $mod+m			exec --no-startup-id noads-spot
bindsym $mod+Home		workspace $ws1
bindsym $mod+End		workspace $ws10
bindsym $mod+Prior	workspace prev
bindsym $mod+Next		workspace next
bindsym $mod+Tab		workspace back_and_forth
bindsym $mod+semicolon		workspace next
bindsym $mod+apostrophe		split horizontal ;; exec $term
bindsym $mod+slash		split vertical ;; exec $term
bindsym $mod+backslash		workspace back_and_forth
bindsym $mod+1		workspace $ws1
bindsym $mod+2		workspace $ws2
bindsym $mod+3		workspace $ws3
bindsym $mod+4		workspace $ws4
bindsym $mod+5		workspace $ws5
bindsym $mod+6		workspace $ws6
bindsym $mod+7		workspace $ws7
bindsym $mod+8		workspace $ws8
bindsym $mod+9		workspace $ws9
bindsym $mod+0		workspace $ws10
bindsym $mod+F1		exec --no-startup-id hdmi-layout
bindsym $mod+F2		restart
bindsym $mod+F3		exec --no-startup-id displayselect
bindsym $mod+F4		exec --no-startup-id prompt "Hibernate computer?" "$hibernate"
bindsym $mod+F5		exec --no-startup-id $netrefresh
bindsym $mod+F6		exec --no-startup-id torwrap
bindsym $mod+F7		exec --no-startup-id td-toggle
bindsym $mod+F8		exec --no-startup-id mailsync
bindsym $mod+F9		exec --no-startup-id dmenumount
bindsym $mod+F10	exec --no-startup-id dmenuumount
bindsym $mod+F11	exec --no-startup-id ducksearch
bindsym $mod+F12	exec $term -e nmtui
bindsym $mod+Up			focus up
bindsym $mod+Down		focus down
bindsym $mod+plus		exec --no-startup-id pulsemixer --change-volume +5 && pkill -SIGRTMIN+6 ${STATUSBAR:-i3blocks}
bindsym $mod+minus		exec --no-startup-id pulsemixer --change-volume -5 && pkill -SIGRTMIN+6 ${STATUSBAR:-i3blocks}
bindsym $mod+less		exec --no-startup-id playerctl previous
bindsym $mod+greater		exec --no-startup-id playerctl next
bindsym $mod+bracketleft	exec --no-startup-id playerctl position 10-
bindsym $mod+bracketright		exec --no-startup-id playerctl position 10+
bindsym Print			exec --no-startup-id maim ~/pics/pic-full-"$(date '+%y%m%d-%H%M-%S').png"
bindsym $mod+Print		exec --no-startup-id dmenurecord
bindsym $mod+Delete		exec --no-startup-id dmenurecord kill

# ---- Shift ----
bindsym $mod+Shift+Return	exec --no-startup-id st -d "`xcwd`"
bindsym $mod+Shift+space	floating toggle
bindsym $mod+Shift+Escape	exec --no-startup-id prompt "Exit i3?" "i3 exit"
#bindsym $mod+Shift+grave
#bindsym $mod+Shift+Insert
bindsym $mod+Shift+BackSpace	exec --no-startup-id prompt "Reboot computer?" "$reboot"
bindsym $mod+Shift+Delete	exec --no-startup-id pulsemixer --mute ; exec --no-startup-id playerctl -a pause ; exec --no-startup-id pauseallmpv; workspace 0; exec $term -e htop ; exec $term -e lf
bindsym $mod+Shift+q		[con_id="__focused__" instance="^(?!dropdown_).*$"] exec --no-startup-id kill -9 `xdotool getwindowfocus getwindowpid`
bindsym $mod+Shift+w		exec $term -e nmtui
# bindsym $mod+Shift+e
bindsym $mod+Shift+r		exec --no-startup-id winresize
bindsym $mod+Shift+t		gaps inner current set $inner_gaps; gaps outer current set $outer_gaps
bindsym $mod+Shift+y		exec --no-startup-id i3resize left
bindsym $mod+Shift+u		exec --no-startup-id i3resize down
bindsym $mod+Shift+i		exec --no-startup-id i3resize up
bindsym $mod+Shift+o		exec --no-startup-id i3resize right
bindsym $mod+Shift+p		exec --no-startup-id playerctl pause
bindsym $mod+Shift+a		exec $term -e pulsemixer
bindsym $mod+Shift+s		gaps inner current minus 5
bindsym $mod+Shift+d		gaps inner current set 0; gaps outer current set 0
bindsym $mod+Shift+f		mode "$freeze" ;; exec --no-startup-id notify-send "dis-free mode activated" ;; exec --no-startup-id notify-send "DUNST_COMMAND_PAUSE"
set $freeze !
mode "$freeze" {
  bindsym $mod+Shift+F11 fullscreen toggle
  bindsym $mod+Shift+f mode "default" ;; exec --no-startup-id notify-send "DUNST_COMMAND_RESUME"
}
bindsym $mod+Shift+g		exec --no-startup-id gimp; workspace $ws5
bindsym $mod+Shift+h		move left 30
bindsym $mod+Shift+j		move down 30
bindsym $mod+Shift+k		move up 30
bindsym $mod+Shift+l		move right 30
bindsym $mod+Shift+z		    gaps outer current minus 5
bindsym $mod+Shift+x		    exec --no-startup-id prompt "Shutdown computer?" "$shutdown"
bindsym $mod+Shift+c		    exec --no-startup-id camtoggle
bindsym $mod+Shift+v            exec --no-startup-id mcrcon  -H 34.107.17.22 -p XonG0d time set day
bindsym $mod+Shift+b		    floating toggle; sticky toggle; exec --no-startup-id hover left
bindsym $mod+Shift+n		    floating toggle; sticky toggle; exec --no-startup-id hover right
bindsym $mod+Shift+m		    exec --no-startup-id pulsemixer --toggle-mute && pkill -SIGRTMIN+6 ${STATUSBAR:-i3blocks}
bindsym $mod+Shift+Home		    move container to workspace $ws1
bindsym $mod+Shift+End		    move container to workspace $ws10
bindsym $mod+Shift+Prior	    move container to workspace prev
bindsym $mod+Shift+Next		    move container to workspace next
bindsym $mod+Shift+apostrophe	split horizontal ;; exec --no-startup-id st -d "`xcwd`"
bindsym $mod+Shift+slash	    split vertical ;; exec --no-startup-id st -d "`xcwd`"

bindsym $mod+Shift+1	    move container to workspace $ws1
bindsym $mod+Shift+2	    move container to workspace $ws2
bindsym $mod+Shift+3	    move container to workspace $ws3
bindsym $mod+Shift+4	    move container to workspace $ws4
bindsym $mod+Shift+5	    move container to workspace $ws5
bindsym $mod+Shift+6	    move container to workspace $ws6
bindsym $mod+Shift+7	    move container to workspace $ws7
bindsym $mod+Shift+8	    move container to workspace $ws8
bindsym $mod+Shift+9	    move container to workspace $ws9
bindsym $mod+Shift+0	    move container to workspace $ws10
bindsym $mod+Shift+Up		    move up
bindsym $mod+Shift+Down		    move down
bindsym $mod+Shift+Left		    move left
bindsym $mod+Shift+Right	    move right
bindsym $mod+Shift+plus		    exec --no-startup-id pulsemixer --change-volume +10 && pkill -SIGRTMIN+6 ${STATUSBAR:-i3blocks}
bindsym $mod+Shift+minus	    exec --no-startup-id pulsemixer --change-volume -10 && pkill -SIGRTMIN+6 ${STATUSBAR:-i3blocks}
bindsym $mod+Shift+less		    exec --no-startup-id playerctl position 0
bindsym $mod+Shift+bracketleft	exec --no-startup-id playerctl position 120-
bindsym $mod+Shift+bracketright exec --no-startup-id playerctl position 120+
bindsym Shift+Print		        exec --no-startup-id maimpick

# ---- Ctrl ----
bindsym $mod+Ctrl+h		    move workspace to output left
bindsym $mod+Ctrl+j		    move workspace to output down
bindsym $mod+Ctrl+k		    move workspace to output up
bindsym $mod+Ctrl+l		    move workspace to output right
bindsym $mod+Ctrl+Up		move workspace to output up
bindsym $mod+Ctrl+Down		move workspace to output down
bindsym $mod+Ctrl+Left		move workspace to output left
bindsym $mod+Ctrl+Right		move workspace to output right
bindsym $mod+Ctrl+plus		exec --no-startup-id pulsemixer --change-volume +1 && pkill -SIGRTMIN+6 ${STATUSBAR:-i3blocks}
bindsym $mod+Ctrl+minus	    exec --no-startup-id pulsemixer --change-volume -1 && pkill -SIGRTMIN+6 ${STATUSBAR:-i3blocks}

# #---Extra XF86 Keys---# #
bindsym XF86Launch1										exec --no-startup-id xset dpms force off
bindsym XF86AudioMute									exec --no-startup-id pulsemixer --toggle-mute && pkill -SIGRTMIN+6 ${STATUSBAR:-i3blocks}
bindsym XF86AudioLowerVolume					        exec --no-startup-id pulsemixer --change-volume -5 && pkill -SIGRTMIN+6 ${STATUSBAR:-i3blocks}
bindsym Shift+XF86AudioLowerVolume		                exec --no-startup-id pulsemixer --change-volume -10 && pkill -SIGRTMIN+6 ${STATUSBAR:-i3blocks}
bindsym Control+XF86AudioLowerVolume	                exec --no-startup-id pulsemixer --change-volume -1 && pkill -SIGRTMIN+6 ${STATUSBAR:-i3blocks}
bindsym XF86AudioRaiseVolume					        exec --no-startup-id pulsemixer --change-volume +5 && pkill -SIGRTMIN+6 ${STATUSBAR:-i3blocks}
bindsym Shift+XF86AudioRaiseVolume		                exec --no-startup-id pulsemixer --change-volume +10 && pkill -SIGRTMIN+6 ${STATUSBAR:-i3blocks}
bindsym Control+XF86AudioRaiseVolume	                exec --no-startup-id pulsemixer --change-volume +1 && pkill -SIGRTMIN+6 ${STATUSBAR:-i3blocks}
bindsym XF86PowerOff									exec --no-startup-id prompt "Shutdown computer?" "$shutdown"
bindsym XF86Calculator								    exec --no-startup-id ddspawn dropdowncalc -f mono:pixelsize=24
bindsym XF86Explorer									exec $term -e lf
bindsym XF86WWW											exec --no-startup-id $BROWSER
bindsym XF86ScreenSaver								    exec --no-startup-id i3lock-fancy
bindsym XF86MyComputer								    exec $term -e lf
bindsym XF86AudioNext									exec --no-startup-id playerctl next
bindsym XF86AudioPlay									exec --no-startup-id playerctl play-pause
bindsym XF86AudioPrev									exec --no-startup-id playerctl previous
bindsym XF86Eject										exec --no-startup-id playerctl stop
bindsym XF86AudioRewind								    exec --no-startup-id playerctl position 10-
bindsym XF86AudioForward							    exec --no-startup-id playerctl position 10+
bindsym XF86HomePage									exec $BROWSER https://github.com/xon-dev/
bindsym XF86Reload										restart
bindsym XF86TouchpadToggle						        exec --no-startup-id toggletouchpad
bindsym XF86TouchpadOn								    exec --no-startup-id synclient TouchpadOff=0
bindsym XF86TouchpadOff								    exec --no-startup-id synclient TouchpadOff=1
bindsym XF86Suspend										exec --no-startup-id i3lock-fancy
bindsym XF86Close										kill
bindsym XF86WebCam										exec --no-startup-id camtoggle
bindsym XF86Mail										exec $term -e neomutt
bindsym XF86Messenger									exec $term -e weechat
bindsym XF86Search										exec $BROWSER https://duckduckgo.com
bindsym XF86MonBrightnessDown					        exec --no-startup-id brightnessctl set 15%-
bindsym XF86MonBrightnessUp						        exec --no-startup-id brightnessctl set 15%+
bindsym XF86AudioMedia								    exec --no-startup-id noads-spot
bindsym XF86Display										exec --no-startup-id displayselect
bindsym XF86Documents									exec $term -e lf ~/docs
bindsym XF86WLAN										exec $netrefresh
bindsym $mod+Left										exec --no-startup-id playerctl position 10-
bindsym $mod+Right										exec --no-startup-id playerctl position 10+

exec_always --no-startup-id xkb-switch --i3
exec_always --no-startup-id hdmi-layout
