#!/bin/bash

main(){
	for bat in /sys/class/power_supply/BAT?
	do
		cap=$(cat "$bat"/capacity 2>/dev/null) || break
		stat=$(sed "s/[Dd]ischarging//;s/[Nn]ot charging//;s/[Cc]harging//;s/[Uu]nknown//;s/[Ff]ull//" "$bat"/status)

		# If it is discharging and 25% or less, we will add a  as a warning.
		[ "$cap" -le 25 ] && [ "$stat" = "" ] && warn=""

		local value="$stat$warn $cap"
		local before="<span color='$blu' bgcolor='$bla'>$lf</span>"
		local after="<span color='$bla' bgcolor='$blu'>$lf</span>"
		local text="<span color='$bla' bgcolor='$blu'> $value </span>"
		[ ! "$value" == "" ] && echo -e "$before$text$after"

		unset warn
	done | sed 's/ *$//'
}
