#!/usr/bin/env bash

main() {
  local value ip='35.198.176.63'
    if [ ! "$(ping -q -w 1 -c 1 $ip)" ]; then
        value="[no connection]"
    else
        value="$(mcrcon  -H $ip -p `cat $HOME/.config/i3blocks/min_pass` list | paste -sd '' | sed -e 's/There are /[/;s/ of a max of /\//;s/ players online:.*/] players/;')"
    fi
    local before="<span color='$mag' bgcolor='$bla'>$lf</span>"
    local after="<span color='$bla' bgcolor='$mag'>$lf</span>"
    local text="<span color='$bla' bgcolor='$mag'> $value </span>"
    [ ! "$value" == "" ] && echo -e "$before$text$after"
    case $BLOCK_BUTTON in
        1) notify-send "$(mcrcon -H $ip -p `cat $HOME/.config/i3blocks/min_pass` list | sed -e 's/^.*: //;s/.\[0m$//' | tr ' ' '\n')" ;;
    esac
}
