#!/bin/bash

# filter() { mpc | sed -E "s/^volume: n\\/a.*//;" | sed -E "s/\\&/&amp;/g;s/\[paused\].*/ /g;s/\[playing\].*/ /g;s/^volume:[0-9]+%\s+//;s/repeat: on\s+/ /;s/repeat: off\s+//;s/random: on\s+/ /;s/random: off\s+//;s/single: on\s+/ /;s/single: off\s+//;s/consume: on\s+/ /;s/consume: off//;" | paste -sd '';}
filter() { mpc | sed -E "s/^volume: n\\/a.*//;" | sed -E "s/\\&/&amp;/g;s/\[paused\].*/ /g;s/\[playing\].*/ /g;s/^volume:[0-9].*//;" | paste -sd '';}

main() {
	$(pidof -x bar_mus &>/dev/null) || $(bar_mus &>/dev/null &)

	local value=$(filter)
	# local prefix="<span font='FontAwesome'>\uf017</span> "
	local before="<span color='${BLU}' bgcolor='${BLA}'></span>"
	local after="<span color='${BLA}' bgcolor='${BLU}'></span>"
	local text="<span color='${BLA}' bgcolor='${BLU}'> ${value} </span>"
	[ ! "${value}" == "" ] && echo -e "${before}${text}${after}"

	case $BLOCK_BUTTON in
		1) mpc toggle ;;
		3) setsid -f "$TERMINAL" -e ncmpcpp ;;
		4) mpc next	;;
		5) mpc prev	;;
	esac
}
