#!/usr/bin/env bash

main() {
	value=$([ -f /tmp/recordingicon ] && cat /tmp/recordingicon || echo "")
	local before="<span color='$gra' bgcolor='$BLA'>$lu</span>"
	local text="<span color='$gra' bgcolor='$bla'>$value</span>"

	[ "$value" == "" ] || echo -e "$before$text"
}
