#!/usr/bin/bash

main() {
  local value=" $(date '+%y-%m-%d')"
  local value2="$(date '+%a')"
  local value3="$(date '+%H:%M:%S')"
  local before="<span color='$TEA' bgcolor='$BLA'>$LF</span>"
	local text="<span color='$BLA' bgcolor='$TEA'> $value </span>"
	local after="<span color='$TEA' bgcolor='$MAG'>$RF</span>"
	local text2="<span color='$BLA' bgcolor='$MAG'> $value2 </span>"
  local after2="<span color='$RED' bgcolor='$MAG'>$LF</span>"
	local text3="<span color='$BLA' bgcolor='$RED'> $value3 </span>"
  local after3="<span color='$BLA' bgcolor='$RED'>$LF</span>"

	[ ! "$value" == "" ] && echo -e "$before$text$after$text2$after2$text3$after3"

	case $BLOCK_BUTTON in
		1) setsid -f "$TERMINAL" -e calcurse ;;
	esac
}
