#!/usr/bin/bash

main() {
  local value=" $(date '+%y-%m-%d')"
  local value2="$(date '+%a')"
  local value3="$(date '+%H:%M:%S')"
  local before="<span color='$tea' bgcolor='$bla'>$lf</span>"
	local text="<span color='$bla' bgcolor='$tea'> $value </span>"
	local after="<span color='$tea' bgcolor='$mag'></span>"
	local text2="<span color='$bla' bgcolor='$mag'> $value2 </span>"
  local after2="<span color='$red' bgcolor='$mag'></span>"
	local text3="<span color='$bla' bgcolor='$red'> $value3 </span>"
  local after3="<span color='$bla' bgcolor='$red'>$lf</span>"

	[ ! "$value" == "" ] && echo -e "$before$text$after$text2$after2$text3$after3"

	case $BLOCK_BUTTON in
		1) setsid -f "$TERMINAL" -e calcurse ;;
	esac
}
