#!/usr/bin/env bash

clip() { xtitle | xclip -selection clipboard; }

main() {
	pidof -x bar_tit &>/dev/null || $(bar_tit &>/dev/null &)

	local value="$(xtitle -t 40)"
	case $BLOCK_BUTTON in
		1) clip | notify-send "Clipboard" "Title yanked" ;;
	esac

	local text="<span color='$gra' bgcolor='$bla'> $value </span>"

	[ ! "$value" == "" ] && echo -e "$text"
}
