#!/bin/sh

link="${XDG_DATA_HOME:-$HOME/.local/share}/tmp/wea"

upd() { curl -sf "wttr.in/$LOCATION" > "$link"; }

show() { sed "16q;d" "$link" |
	grep -wo "[0-9]*%" | sort -rn | sed "s/^//g;1q" | tr -d '\n'
sed "13q;d" "$link" | grep -o "m\\([-+]\\)*[0-9]\\+" |
	sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' |
	awk '{print " " $1 "°","" $2 "°"}' ;}

main () {
	upd
	local value
	if [ ! "$(ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3`)" ]; then
		value="[no connection]"
	elif [ "$(curl wttr.in --silent | wc -l)" -lt 3 ]; then
		value="[site down]"
	else
		value="$(show)"
	fi
	local before="<span color='$yel' bgcolor='$bla'></span>"
	local after="<span color='$bla' bgcolor='$yel'></span>"
	local text="<span color='$bla' bgcolor='$yel'> $value </span>"
	[ ! "$value" == "" ] && echo -e "$before$text$after"

	case $BLOCK_BUTTON in
		1) setsid -f "$TERMINAL" -e less -Srf "$link" ;;
		3) upd && pkill -SIGRTMIN+4 i3blocks ;;
	esac
}
