#!/bin/bash

readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DEV=$1

# Colors
readonly whi='#fdf6e3'
readonly gra='#aaaaaa'
readonly bla='#222222'
readonly red='#e5786d'
readonly yel='#ffe161'
readonly gre='#cae682'
readonly blu='#5283d7'
readonly mag='#b698d9'
readonly cya='#a8c6f2'
readonly tea='#18A7B5'

# Shapes
# U+E0B0 - U+E0C8

# Arrow {{{
readonly rfa=''
readonly rua=''
readonly lfa=''
readonly lua=''
# }}}

# Rounded {{{
readonly rfr=''
readonly rur=''
readonly lfr=''
readonly lur=''
# }}}

# Slab {{{
readonly rfs=''
readonly rus=''
readonly lfs=''
readonly lus=''
# }}}

# Slab flipped {{{
readonly rfsf=''
readonly rusf=''
readonly lfsf=''
readonly lusf=''
# }}}

# Fire {{{
readonly rff=''
readonly ruf=''
readonly lff=''
readonly luf=''
# }}}

# Dots {{{
readonly rfd=''
readonly rud=''
readonly lfd=''
readonly lud=''
# }}}

# Global {{{
readonly rf=$rfs
readonly ru=$rus
readonly lf=$lfs
readonly lu=$lus
# }}}

FG=$GRA
BG=$BLA

if [ "$#" -ne 1 ]
then
    notify-send "usage: ${0} <dev>"
    exit 1
fi

if [ ! -e $DIR/$DEV ]
then
    notify-send "block '$DEV' not found"
    exit 1
else
    . $DIR/$DEV

    echo -e "$(main)"
fi

# vim: set foldmethod=marker ts=2 sw=2 tw=80 noet :
