#!/bin/bash

readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DEV=$1

# Colors
readonly WHI='#fdf6e3'
readonly GRA='#aaaaaa'
readonly BLA='#222222'
readonly RED='#e5786d'
readonly YEL='#ffe161'
readonly GRE='#cae682'
readonly BLU='#5283d7'
readonly MAG='#b698d9'
readonly CYA='#a8c6f2'
readonly TEA='#18A7B5'

# Shapes
readonly LF=''
readonly RF=''
readonly LU=''
readonly RU=''

FG=$GRA
BG=$BLA

if [ "$#" -ne 1 ]
then
    notify-send "usage: ${0} <dev>"
    exit 1
fi

if [ ! -e $DIR/$DEV ]
then
    notify-send "block '$DEV' not found"
    exit 1
else
    . $DIR/$DEV

    echo -e "$(main)"
fi
