#!/bin/bash

readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DEV=$1

# Colors
readonly whi='#fdf6e3'
readonly gra='#aaaaaa'
readonly bla='#222222'
readonly red='#e5786d'
readonly yel='#ffe161'
readonly gre='#cae682'
readonly blu='#5283d7'
readonly mag='#b698d9'
readonly cya='#a8c6f2'
readonly tea='#18A7B5'

# Shapes
# U+E0B0 - U+E0C8
readonly lf=''
readonly rf=''
readonly lu=''
readonly ru=''

FG=$GRA
BG=$BLA

if [ "$#" -ne 1 ]
then
    notify-send "usage: ${0} <dev>"
    exit 1
fi

if [ ! -e $DIR/$DEV ]
then
    notify-send "block '$DEV' not found"
    exit 1
else
    . $DIR/$DEV

    echo -e "$(main)"
fi
