#!/bin/sh

# xinitrc runs automatically when you run startx.

export STATUSBAR="i3blocks" # Uncomment this line when using i3.

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/xprofile" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/xprofile"

hdmi-layout &
ssh-agent i3
