#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

mpd && mpdup &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
calcurse --daemon &
hsetroot -solid "#010F0F" &
xcompmgr &		# xcompmgr for transparency
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources &	# Uncomment to use Xresources colors/settings on startup
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
xinput set-prop SynPS/2\ Synaptics\ TouchPad libinput\ Tapping\ Enabled 1 &
xinput set-prop SynPS/2\ Synaptics\ TouchPad libinput\ Natural\ Scrolling\ Enabled 1 &
setbg &			# set the background with the `setbg` script
gxkb &
