#!/bin/sh

# This file runs when a DM logs you into a graphical session.

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
# dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

killall pulseaudio&
pulseaudio --daemonize&
unicode_start &
# mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
calcurse --daemon &
hsetroot -solid "#121211" &
# xcompmgr &		# xcompmgr for transparency
picom --experimental-backend -f -D 5 &
# xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources &	# Uncomment to use Xresources colors/settings on startup
dunst &			# dunst for notifications
xset s 1200 600 &
xset dpms 600 900 1200 & # Screen lock
unclutter &		# Remove mouse when idle
xinput set-prop "ELAN0515:01 04F3:3142 Touchpad" libinput\ Tapping\ Enabled 1 &
xinput set-prop "ELAN0515:01 04F3:3142 Touchpad" libinput\ Natural\ Scrolling\ Enabled 1 &
setbg &			# set the background with the `setbg` script
mpDris2 &
libinput-gestures-setup start&
# xss-lock i3lockk&
# udiskie &
