#!/bin/sh
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

command=~/.config/i3blocks/blocks/wrap $BLOCK_NAME
separator=false
separator_block_width=0
markup=pango

[tit]
interval=once
signal=1

[rec]
interval=once
signal=2

[mus]
interval=once
signal=3

[wea]
interval=180
signal=4

[xkb]
interval=1
signal=5

[tim]
interval=1
