#!/bin/sh
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

command=~/.local/bin/blocks/wrap $BLOCK_NAME
separator=false
separator_block_width=0
markup=pango

[title]
signal=1
interval=once

[record]
interval=once
signal=2

[mus]
signal=3
interval=once

[time]
interval=1
